import org.apache.tools.ant.filters.ReplaceTokens

buildscript {
    repositories {
        mavenCentral()
        maven {
            name = 'Bintray Plugins'
            url = 'https://plugins.gradle.org/m2'
        }
        maven {
          name 'Groovy jfrog'
          url 'https://groovy.jfrog.io/artifactory/libs-release'
        }
    }
    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:0.4'
    }
}

apply plugin: 'com.jfrog.bintray'

group = 'org.graniteds'
version = granitedsVersion

ext.jetty8Version = '8.1.15.v20140411'
ext.jetty9Version = '9.1.2.v20140210'

def timestamp = new Date().format('yyyyMMddHHmmss')
try {
    def gitFolder = "$projectDir/.git/"
    def head = new File(gitFolder + 'HEAD').text.split(':')
    def isCommit = head.length == 1
    def refHead = new File(gitFolder + (isCommit ? 'HEAD' : head[1].trim()))
    timestamp = new Date(refHead.lastModified()).format('yyyyMMddHHmmss')
} catch (Exception ignored) {}

ext.pluginVersion = granitedsVersion.contains('-SNAPSHOT') ?
        granitedsVersion.replace('-SNAPSHOT', ".v$timestamp") :
        granitedsVersion.replaceAll(/(\d+\.\d+)\..*/, "\$1.v$timestamp")

ext.javadocLinks = [
    "http://docs.oracle.com/javase/7/docs/api/",
    "http://docs.oracle.com/javaee/7/api/"
]

// Set up repository for all subprojects
configure(subprojects) {
    repositories {
        mavenCentral()
    }
}

// Apply Java plugin and config
configure(subprojects.findAll { it.name in ['granite-common', 'granite-amf', 'granite-jmf', 'granite-jmf-java8', 'granite-server-core', 'granite-server-servlet3'] }) { subproject ->
    apply plugin: 'java'
    apply plugin: 'eclipse'

    sourceCompatibility = 1.6
    targetCompatibility = 1.6

    dependencies {
        testCompile 'junit:junit:4.11'
    }

    task sourcesJar(type: Jar, dependsOn: classes) {
        classifier = 'sources'
        from sourceSets.main.allSource
    }

    jar {
        metaInf {
            from 'LICENSE.txt'
        }
    }

    artifacts {
        archives sourcesJar
    }

    test {
        workingDir = subproject.rootDir
        ignoreFailures = true
    }
}

// Minimal coreProjects and allProjects
ext.coreProjects = [
    ':granite-server-core',
    ':granite-server-servlet3',
]

ext.allProjects = coreProjects + [
    ':granite-common'
]